export const translations = {
  en: {
    // Navigation
    dashboard: '📊 Dashboard',
    addTenant: '➕ Add Tenant',
    tenants: '👥 Tenants',
    billing: '🧾 Billing',
    payments: '💰 Payments',
    logout: '🚪 Logout',
    language: 'नेपाली',

    // Dashboard
    goodDay: 'Good day, Yubaraj dai 👋',
    overview: 'Here is your property overview',
    totalRooms: 'Total Rooms',
    occupied: '● Occupied',
    vacant: '○ Vacant',
    activeTenants: 'Active Tenants',
    collected: 'Collected',
    totalDue: 'Total Due',
    unpaidBills: 'unpaid bill(s)',
    view: 'View →',
    owner: 'Owner',
    rooms: 'rooms',
    occupiedOf: 'occupied',

    // Tenant form
    addNewTenant: '🏠 Add New Tenant',
    fillDetails: 'Fill all details carefully. All info can be edited later.',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    fatherName: "Father's Name",
    grandfatherName: "Grandfather's Name",
    profession: 'Profession',
    citizenshipId: 'Citizenship ID / National ID',
    contactInfo: 'Contact Information',
    phone: 'Phone Number',
    email: 'Email Address',
    temporaryAddress: 'Temporary Address',
    permanentAddress: 'Permanent Address',
    roomInfo: 'Room and Lease Information',
    selectRoom: 'Select Room',
    selectVacantRoom: '-- Select a vacant room --',
    roomOwner: 'Room Owner Name',
    numberOfPeople: 'Number of People in Room',
    leaseStart: 'Lease Start Date',
    leaseEnd: 'Lease End Date',
    advanceAmount: 'Advance Amount',
    saveTenant: 'Save Tenant Information',
    backToDashboard: '← Back to Dashboard',
    pleaseFill: 'Please fill full name and select a room.',
    tenantSaved: 'Tenant saved successfully!',

    // Tenant list
    tenantList: '👥 Tenant List',
    activeTenantCount: 'active tenant(s)',
    edit: '✏️ Edit',
    remove: '🚪 Remove',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    editing: '✏️ Editing',
    father: 'Father',
    grandfather: 'Grandfather',
    peopleInRoom: 'People in room',
    advance: 'Advance',
    removeConfirm: 'Are you sure you want to remove this tenant?',
    tenantUpdated: 'Tenant updated successfully!',

    // Billing
    monthlyBilling: '🧾 Monthly Billing',
    selectTenant: 'Select Tenant',
    noActiveTenants: 'No active tenants found.',
    billingPeriod: 'Billing Period',
    month: 'Month',
    year: 'Year',
    monthlyCharges: 'Monthly Charges',
    rent: 'Rent Amount',
    electricityUnits: 'Electricity Units Used',
    electricityRate: 'Electricity Rate per Unit',
    electricityCharge: 'Electricity Charge',
    waterCharge: 'Water Charge',
    dustbinCharge: 'Dustbin Cleaning Charge',
    damageCharge: 'Damage Charge',
    billSummary: 'Bill Summary',
    electricity: 'Electricity',
    water: 'Water',
    dustbin: 'Dustbin',
    damage: 'Damage',
    totalBill: 'Total Bill',
    paymentDetails: 'Payment Details',
    advanceUsed: 'Advance Used',
    paidAmount: 'Paid Amount',
    paymentMethod: 'Payment Method',
    notes: 'Notes',
    dueBal: 'Due Balance',
    fullyPaid: 'Fully Paid ✅',
    extra: 'Extra',
    saveBill: 'Save Bill',
    billSaved: 'Bill saved successfully!',

    // Payments
    paymentsTitle: '💰 Payments',
    totalCollected: 'Total Collected',
    totalDueAmt: 'Total Due',
    totalBills: 'Total Bills',
    paid: '✅ Paid',
    unpaid: '❌ Unpaid',
    room: 'Room',
  },

  np: {
    // Navigation
    dashboard: '📊 ड्यासबोर्ड',
    addTenant: '➕ भाडावाला थप्नुस्',
    tenants: '👥 भाडावालाहरू',
    billing: '🧾 बिल',
    payments: '💰 भुक्तानी',
    logout: '🚪 बाहिर निस्कनुस्',
    language: 'English',

    // Dashboard
    goodDay: 'नमस्ते, युबराज दाई 👋',
    overview: 'तपाईंको सम्पत्तिको विवरण',
    totalRooms: 'जम्मा कोठाहरू',
    occupied: '● भरिएको',
    vacant: '○ खाली',
    activeTenants: 'सक्रिय भाडावालाहरू',
    collected: 'संकलन भएको',
    totalDue: 'जम्मा बाँकी',
    unpaidBills: 'तिर्न बाँकी बिल',
    view: 'हेर्नुस् →',
    owner: 'घरधनी',
    rooms: 'कोठाहरू',
    occupiedOf: 'भरिएको',

    // Tenant form
    addNewTenant: '🏠 नयाँ भाडावाला थप्नुस्',
    fillDetails: 'सबै विवरण ध्यानपूर्वक भर्नुस्। पछि सम्पादन गर्न सकिन्छ।',
    personalInfo: 'व्यक्तिगत जानकारी',
    fullName: 'पूरा नाम',
    fatherName: 'बुबाको नाम',
    grandfatherName: 'हजुरबुबाको नाम',
    profession: 'पेशा',
    citizenshipId: 'नागरिकता नम्बर / राष्ट्रिय परिचयपत्र',
    contactInfo: 'सम्पर्क जानकारी',
    phone: 'फोन नम्बर',
    email: 'इमेल ठेगाना',
    temporaryAddress: 'अस्थायी ठेगाना',
    permanentAddress: 'स्थायी ठेगाना',
    roomInfo: 'कोठा र सम्झौता जानकारी',
    selectRoom: 'कोठा छान्नुस्',
    selectVacantRoom: '-- खाली कोठा छान्नुस् --',
    roomOwner: 'घरधनीको नाम',
    numberOfPeople: 'कोठामा बस्ने मान्छेको संख्या',
    leaseStart: 'सम्झौता सुरु मिति',
    leaseEnd: 'सम्झौता सकिने मिति',
    advanceAmount: 'अग्रिम रकम',
    saveTenant: 'भाडावालाको जानकारी सेभ गर्नुस्',
    backToDashboard: '← ड्यासबोर्डमा फर्कनुस्',
    pleaseFill: 'कृपया पूरा नाम र कोठा छान्नुस्।',
    tenantSaved: 'भाडावालाको जानकारी सफलतापूर्वक सेभ भयो!',

    // Tenant list
    tenantList: '👥 भाडावालाहरूको सूची',
    activeTenantCount: 'सक्रिय भाडावाला',
    edit: '✏️ सम्पादन',
    remove: '🚪 हटाउनुस्',
    saveChanges: 'परिवर्तन सेभ गर्नुस्',
    cancel: 'रद्द गर्नुस्',
    editing: '✏️ सम्पादन हुँदैछ',
    father: 'बुबा',
    grandfather: 'हजुरबुबा',
    peopleInRoom: 'कोठामा मान्छे',
    advance: 'अग्रिम',
    removeConfirm: 'के तपाईं यो भाडावाला हटाउन निश्चित हुनुहुन्छ?',
    tenantUpdated: 'भाडावालाको जानकारी सफलतापूर्वक अपडेट भयो!',

    // Billing
    monthlyBilling: '🧾 मासिक बिल',
    selectTenant: 'भाडावाला छान्नुस्',
    noActiveTenants: 'कुनै सक्रिय भाडावाला फेला परेन।',
    billingPeriod: 'बिलिङ अवधि',
    month: 'महिना',
    year: 'साल',
    monthlyCharges: 'मासिक शुल्कहरू',
    rent: 'भाडा रकम',
    electricityUnits: 'बिजुली युनिट प्रयोग',
    electricityRate: 'प्रति युनिट दर',
    electricityCharge: 'बिजुली शुल्क',
    waterCharge: 'पानी शुल्क',
    dustbinCharge: 'फोहोर शुल्क',
    damageCharge: 'क्षति शुल्क',
    billSummary: 'बिल सारांश',
    electricity: 'बिजुली',
    water: 'पानी',
    dustbin: 'फोहोर',
    damage: 'क्षति',
    totalBill: 'जम्मा बिल',
    paymentDetails: 'भुक्तानी विवरण',
    advanceUsed: 'अग्रिम रकम प्रयोग',
    paidAmount: 'तिरेको रकम',
    paymentMethod: 'भुक्तानी तरिका',
    notes: 'कैफियत',
    dueBal: 'बाँकी रकम',
    fullyPaid: 'पूर्ण भुक्तानी ✅',
    extra: 'बढी',
    saveBill: 'बिल सेभ गर्नुस्',
    billSaved: 'बिल सफलतापूर्वक सेभ भयो!',

    // Payments
    paymentsTitle: '💰 भुक्तानीहरू',
    totalCollected: 'जम्मा संकलन',
    totalDueAmt: 'जम्मा बाँकी',
    totalBills: 'जम्मा बिलहरू',
    paid: '✅ तिरिएको',
    unpaid: '❌ बाँकी',
    room: 'कोठा',
  }
}